-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'user@fake-gmail.com',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'admin@fake-gmail.com',
        TRUE);


INSERT INTO pokemon (id, name, type, image_url, type_url)
VALUES (1, 'Bulbasaur', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png', 'https://pokeapi.co/api/v2/type/12/'),
       (2, 'Ivysaur', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', 'https://pokeapi.co/api/v2/type/12/'),
       (3, 'Venusaur', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', 'https://pokeapi.co/api/v2/type/12/'),
       (4, 'Charmander', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', 'https://pokeapi.co/api/v2/type/10/'),
       (5, 'Charmeleon', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png', 'https://pokeapi.co/api/v2/type/10/'),
       (6, 'Charizard', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', 'https://pokeapi.co/api/v2/type/10/'),
       (7, 'Squirtle', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png', 'https://pokeapi.co/api/v2/type/11/'),
        (8, 'Wartortle', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png', 'https://pokeapi.co/api/v2/type/11/'),
        (9, 'Blastoise', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png', 'https://pokeapi.co/api/v2/type/11/'),
        (10, 'Caterpie', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png', 'https://pokeapi.co/api/v2/type/7/'),
        (11, 'Metapod', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png', 'https://pokeapi.co/api/v2/type/7/'),
        (12, 'Butterfree', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png', 'https://pokeapi.co/api/v2/type/7/'),
        (13, 'Weedle', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png', 'https://pokeapi.co/api/v2/type/7/'),
        (14, 'Kakuna', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png', 'https://pokeapi.co/api/v2/type/7/'),
        (15, 'Beedrill', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png', 'https://pokeapi.co/api/v2/type/7/'),
        (16, 'Pidgey', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png', 'https://pokeapi.co/api/v2/type/1/'),
        (17, 'Pidgeotto', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png', 'https://pokeapi.co/api/v2/type/1/'),
        (18, 'Pidgeot', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png', 'https://pokeapi.co/api/v2/type/1/'),
        (19, 'Rattata', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png', 'https://pokeapi.co/api/v2/type/1/'),
        (20, 'Raticate', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png', 'https://pokeapi.co/api/v2/type/1/'),
        (21, 'Spearow', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png', 'https://pokeapi.co/api/v2/type/1/'),
        (22, 'Fearow', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png', 'https://pokeapi.co/api/v2/type/1/'),
        (23, 'Ekans', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png', 'https://pokeapi.co/api/v2/type/4/'),
        (24, 'Arbok', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png', 'https://pokeapi.co/api/v2/type/4/'),
        (25, 'Pikachu', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', 'https://pokeapi.co/api/v2/type/13/'),
        (26, 'Raichu', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png', 'https://pokeapi.co/api/v2/type/13/'),
        (27, 'Sandshrew', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png', 'https://pokeapi.co/api/v2/type/5/'),
        (28, 'Sandslash', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png', 'https://pokeapi.co/api/v2/type/5/'),
        (29, 'Nidoran♀', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png', 'https://pokeapi.co/api/v2/type/4/'),
        (30, 'Nidorina', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png', 'https://pokeapi.co/api/v2/type/4/'),
        (31, 'Nidoqueen', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png', 'https://pokeapi.co/api/v2/type/4/'),
        (32, 'Nidoran♂', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png', 'https://pokeapi.co/api/v2/type/4/'),
        (33, 'Nidorino', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png', 'https://pokeapi.co/api/v2/type/4/'),
        (34, 'Nidoking', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png', 'https://pokeapi.co/api/v2/type/4/'),
        (35, 'Clefairy', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png', 'https://pokeapi.co/api/v2/type/18/'),
        (36, 'Clefable', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png', 'https://pokeapi.co/api/v2/type/18/'),
        (37, 'Vulpix', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png', 'https://pokeapi.co/api/v2/type/10/'),
        (38, 'Ninetales', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png', 'https://pokeapi.co/api/v2/type/10/'),
        (39, 'Jigglypuff', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png', 'https://pokeapi.co/api/v2/type/1/'),
        (40, 'Wigglytuff', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png', 'https://pokeapi.co/api/v2/type/1/'),
        (41, 'Zubat', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png', 'https://pokeapi.co/api/v2/type/4/'),
        (42, 'Golbat', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png', 'https://pokeapi.co/api/v2/type/4/'),
        (43, 'Oddish', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png', 'https://pokeapi.co/api/v2/type/12/'),
        (44, 'Gloom', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png', 'https://pokeapi.co/api/v2/type/12/'),
        (45, 'Vileplume', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png', 'https://pokeapi.co/api/v2/type/12/'),
        (46, 'Paras', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png', 'https://pokeapi.co/api/v2/type/7/'),
        (47, 'Parasect', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png', 'https://pokeapi.co/api/v2/type/7/'),
        (48, 'Venonat', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png', 'https://pokeapi.co/api/v2/type/7/'),
        (49, 'Venomoth', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png', 'https://pokeapi.co/api/v2/type/7/'),
        (50, 'Diglett', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png', 'https://pokeapi.co/api/v2/type/5/'),
        (51, 'Dugtrio', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png', 'https://pokeapi.co/api/v2/type/5/'),
        (52, 'Meowth', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png', 'https://pokeapi.co/api/v2/type/1/'),
        (53, 'Persian', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png', 'https://pokeapi.co/api/v2/type/1/'),
        (54, 'Psyduck', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png', 'https://pokeapi.co/api/v2/type/11/'),
        (55, 'Golduck', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png', 'https://pokeapi.co/api/v2/type/11/'),
        (56, 'Mankey', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png', 'https://pokeapi.co/api/v2/type/2/'),
        (57, 'Primeape', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png', 'https://pokeapi.co/api/v2/type/2/'),
        (58, 'Growlithe', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png', 'https://pokeapi.co/api/v2/type/10/'),
        (59, 'Arcanine', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png', 'https://pokeapi.co/api/v2/type/10/'),
        (60, 'Poliwag', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png', 'https://pokeapi.co/api/v2/type/11/'),
        (61, 'Poliwhirl', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png', 'https://pokeapi.co/api/v2/type/11/'),
        (62, 'Poliwrath', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png', 'https://pokeapi.co/api/v2/type/11/'),
        (63, 'Abra', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png', 'https://pokeapi.co/api/v2/type/14/'),
        (64, 'Kadabra', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png', 'https://pokeapi.co/api/v2/type/14/'),
        (65, 'Alakazam', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png', 'https://pokeapi.co/api/v2/type/14/'),
        (66, 'Machop', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png', 'https://pokeapi.co/api/v2/type/2/'),
        (67, 'Machoke', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png', 'https://pokeapi.co/api/v2/type/2/'),
        (68, 'Machamp', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png', 'https://pokeapi.co/api/v2/type/2/'),
        (69, 'Bellsprout', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png', 'https://pokeapi.co/api/v2/type/12/'),
        (70, 'Weepinbell', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png', 'https://pokeapi.co/api/v2/type/12/'),
        (71, 'Victreebel', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png', 'https://pokeapi.co/api/v2/type/12/'),
        (72, 'Tentacool', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png', 'https://pokeapi.co/api/v2/type/11/'),
        (73, 'Tentacruel', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png', 'https://pokeapi.co/api/v2/type/11/'),
        (74, 'Geodude', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png', 'https://pokeapi.co/api/v2/type/6/'),
        (75, 'Graveler', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png', 'https://pokeapi.co/api/v2/type/6/'),
        (76, 'Golem', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png', 'https://pokeapi.co/api/v2/type/6/'),
        (77, 'Ponyta', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png', 'https://pokeapi.co/api/v2/type/10/'),
        (78, 'Rapidash', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png', 'https://pokeapi.co/api/v2/type/10/'),
        (79, 'Slowpoke', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png', 'https://pokeapi.co/api/v2/type/11/'),
        (80, 'Slowbro', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png', 'https://pokeapi.co/api/v2/type/11/'),
        (81, 'Magnemite', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png', 'https://pokeapi.co/api/v2/type/13/'),
        (82, 'Magneton', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png', 'https://pokeapi.co/api/v2/type/13/'),
        (83, 'Farfetchd', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png', 'https://pokeapi.co/api/v2/type/1/'),
        (84, 'Doduo', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png', 'https://pokeapi.co/api/v2/type/1/'),
        (85, 'Dodrio', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png', 'https://pokeapi.co/api/v2/type/1/'),
        (86, 'Seel', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png', 'https://pokeapi.co/api/v2/type/11/'),
        (87, 'Dewgong', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png', 'https://pokeapi.co/api/v2/type/11/'),
        (88, 'Grimer', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png', 'https://pokeapi.co/api/v2/type/4/'),
        (89, 'Muk', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png', 'https://pokeapi.co/api/v2/type/4/'),
        (90, 'Shellder', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png', 'https://pokeapi.co/api/v2/type/11/'),
        (91, 'Cloyster', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png', 'https://pokeapi.co/api/v2/type/11/'),
        (92, 'Gastly', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png', 'https://pokeapi.co/api/v2/type/8/'),
        (93, 'Haunter', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png', 'https://pokeapi.co/api/v2/type/8/'),
        (94, 'Gengar', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png', 'https://pokeapi.co/api/v2/type/8/'),
        (95, 'Onix', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png', 'https://pokeapi.co/api/v2/type/6/'),
        (96, 'Drowzee', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png', 'https://pokeapi.co/api/v2/type/14/'),
        (97, 'Hypno', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png', 'https://pokeapi.co/api/v2/type/14/'),
        (98, 'Krabby', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png', 'https://pokeapi.co/api/v2/type/11/'),
        (99, 'Kingler', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png', 'https://pokeapi.co/api/v2/type/11/'),
        (100, 'Voltorb', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png', 'https://pokeapi.co/api/v2/type/13/'),
        (101, 'Electrode', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png', 'https://pokeapi.co/api/v2/type/13/'),
        (102, 'Exeggcute', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png', 'https://pokeapi.co/api/v2/type/12/'),
        (103, 'Exeggutor', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png', 'https://pokeapi.co/api/v2/type/12/'),
        (104, 'Cubone', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png', 'https://pokeapi.co/api/v2/type/5/'),
        (105, 'Marowak', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png', 'https://pokeapi.co/api/v2/type/5/'),
        (106, 'Hitmonlee', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png', 'https://pokeapi.co/api/v2/type/2/'),
        (107, 'Hitmonchan', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png', 'https://pokeapi.co/api/v2/type/2/'),
        (108, 'Lickitung', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png', 'https://pokeapi.co/api/v2/type/1/'),
        (109, 'Koffing', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png', 'https://pokeapi.co/api/v2/type/4/'),
        (110, 'Weezing', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png', 'https://pokeapi.co/api/v2/type/4/'),
        (111, 'Rhyhorn', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png', 'https://pokeapi.co/api/v2/type/5/'),
        (112, 'Rhydon', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png', 'https://pokeapi.co/api/v2/type/5/'),
        (113, 'Chansey', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png', 'https://pokeapi.co/api/v2/type/1/'),
        (114, 'Tangela', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png', 'https://pokeapi.co/api/v2/type/12/'),
        (115, 'Kangaskhan', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png', 'https://pokeapi.co/api/v2/type/1/'),
        (116, 'Horsea', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png', 'https://pokeapi.co/api/v2/type/11/'),
        (117, 'Seadra', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png', 'https://pokeapi.co/api/v2/type/11/'),
        (118, 'Goldeen', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png', 'https://pokeapi.co/api/v2/type/11/'),
        (119, 'Seaking', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png', 'https://pokeapi.co/api/v2/type/11/'),
        (120, 'Staryu', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png', 'https://pokeapi.co/api/v2/type/11/'),
        (121, 'Starmie', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png', 'https://pokeapi.co/api/v2/type/11/'),
        (122, 'Mr. Mime', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png', 'https://pokeapi.co/api/v2/type/14/'),
        (123, 'Scyther', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png', 'https://pokeapi.co/api/v2/type/7/'),
        (124, 'Jynx', 'Ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png', 'https://pokeapi.co/api/v2/type/15/'),
        (125, 'Electabuzz', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png', 'https://pokeapi.co/api/v2/type/13/'),
        (126, 'Magmar', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png', 'https://pokeapi.co/api/v2/type/10/'),
        (127, 'Pinsir', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png', 'https://pokeapi.co/api/v2/type/7/'),
        (128, 'Tauros', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png', 'https://pokeapi.co/api/v2/type/1/'),
        (129, 'Magikarp', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png', 'https://pokeapi.co/api/v2/type/11/'),
        (130, 'Gyarados', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png', 'https://pokeapi.co/api/v2/type/11/'),
        (131, 'Lapras', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png', 'https://pokeapi.co/api/v2/type/11/'),
        (132, 'Ditto', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png', 'https://pokeapi.co/api/v2/type/1/'),
        (133, 'Eevee', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png', 'https://pokeapi.co/api/v2/type/1/'),
        (134, 'Vaporeon', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png', 'https://pokeapi.co/api/v2/type/11/'),
        (135, 'Jolteon', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png', 'https://pokeapi.co/api/v2/type/13/'),
        (136, 'Flareon', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png', 'https://pokeapi.co/api/v2/type/10/'),
        (137, 'Porygon', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png', 'https://pokeapi.co/api/v2/type/1/'),
        (138, 'Omanyte', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png', 'https://pokeapi.co/api/v2/type/6/'),
        (139, 'Omastar', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png', 'https://pokeapi.co/api/v2/type/6/'),
        (140, 'Kabuto', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png', 'https://pokeapi.co/api/v2/type/6/'),
        (141, 'Kabutops', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png', 'https://pokeapi.co/api/v2/type/6/'),
        (142, 'Aerodactyl', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png', 'https://pokeapi.co/api/v2/type/6/'),
        (143, 'Snorlax', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png', 'https://pokeapi.co/api/v2/type/1/'),
        (144, 'Articuno', 'Ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png', 'https://pokeapi.co/api/v2/type/15/'),
        (145, 'Zapdos', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png', 'https://pokeapi.co/api/v2/type/13/'),
        (146, 'Moltres', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png', 'https://pokeapi.co/api/v2/type/10/'),
        (147, 'Dratini', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png', 'https://pokeapi.co/api/v2/type/16/'),
        (148, 'Dragonair', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png', 'https://pokeapi.co/api/v2/type/16/'),
        (149, 'Dragonite', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png', 'https://pokeapi.co/api/v2/type/16/'),
        (150, 'Mewtwo', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png', 'https://pokeapi.co/api/v2/type/14/'),
        (151, 'Mew', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png', 'https://pokeapi.co/api/v2/type/14/');

