-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        TRUE);


INSERT INTO pokemon (id, name, type, image_url)
VALUES (1, 'Bulbasaur', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png'),
       (2, 'Ivysaur', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png'),
       (3, 'Venusaur', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png'),
       (4, 'Charmander', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png'),
       (5, 'Charmeleon', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png'),
       (6, 'Charizard', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png'),
       (7, 'Squirtle', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png'),
       (8, 'Wartortle', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png'),
       (9, 'Blastoise', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png'),
       (10, 'Caterpie', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png'),
       (11, 'Metapod', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png'),
       (12, 'Butterfree', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png'),
       (13, 'Weedle', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png'),
       (14, 'Kakuna', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png'),
       (15, 'Beedrill', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png'),
       (16, 'Pidgey', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon16.png'),
       (17, 'Pidgeotto', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png'),
       (18, 'Pidgeot', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png'),
       (19, 'Rattata', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png'),
       (20, 'Raticate', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png'),
       (21, 'Spearow', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png'),
       (22, 'Fearow', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png'),
       (23, 'Ekans', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png'),
       (24, 'Arbok', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png'),
       (25, 'Pikachu', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png'),
       (26, 'Raichu', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png'),
       (27, 'Sandshrew', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png'),
       (28, 'Sandslash', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png'),
       (29, 'Nidoran♀', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png'),
       (30, 'Nidorina', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png'),
       (31, 'Nidoqueen', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png'),
       (32, 'Nidoran♂', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png'),
       (33, 'Nidorino', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png'),
       (34, 'Nidoking', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png'),
       (35, 'Clefairy', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png'),
       (36, 'Clefable', 'Fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png'),
       (37, 'Vulpix', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png'),
       (38, 'Ninetales', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png'),
       (39, 'Jigglypuff', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png'),
       (40, 'Wigglytuff', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png'),
       (41, 'Zubat', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png'),
       (42, 'Golbat', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png'),
       (43, 'Oddish', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png'),
       (44, 'Gloom', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png'),
       (45, 'Vileplume', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png'),
       (46, 'Paras', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png'),
       (47, 'Parasect', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png'),
       (48, 'Venonat', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png'),
       (49, 'Venomoth', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png'),
       (50, 'Diglett', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png'),
       (51, 'Dugtrio', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png'),
       (52, 'Meowth', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png'),
       (53, 'Persian', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png'),
       (54, 'Psyduck', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png'),
       (55, 'Golduck', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png'),
       (56, 'Mankey', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png'),
       (57, 'Primeape', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png'),
       (58, 'Growlithe', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png'),
       (59, 'Arcanine', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png'),
       (60, 'Poliwag', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png'),
       (61, 'Poliwhirl', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png'),
       (62, 'Poliwrath', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png'),
       (63, 'Abra', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png'),
       (64, 'Kadabra', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png'),
       (65, 'Alakazam', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png'),
       (66, 'Machop', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png'),
       (67, 'Machoke', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png'),
       (68, 'Machamp', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png'),
       (69, 'Bellsprout', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png'),
       (70, 'Weepinbell', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png'),
       (71, 'Victreebel', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png'),
       (72, 'Tentacool', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png'),
       (73, 'Tentacruel', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png'),
       (74, 'Geodude', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png'),
       (75, 'Graveler', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png'),
       (76, 'Golem', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png'),
       (77, 'Ponyta', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png'),
       (78, 'Rapidash', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png'),
       (79, 'Slowpoke', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png'),
       (80, 'Slowbro', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png'),
       (81, 'Magnemite', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png'),
       (82, 'Magneton', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png'),
       (83, 'Farfetchd', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png'),
       (84, 'Doduo', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png'),
       (85, 'Dodrio', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png'),
       (86, 'Seel', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png'),
       (87, 'Dewgong', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png'),
       (88, 'Grimer', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png'),
       (89, 'Muk', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png'),
       (90, 'Shellder', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png'),
       (91, 'Cloyster', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png'),
       (92, 'Gastly', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png'),
       (93, 'Haunter', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png'),
       (94, 'Gengar', 'Ghost', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png'),
       (95, 'Onix', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png'),
       (96, 'Drowzee', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png'),
       (97, 'Hypno', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png'),
       (98, 'Krabby', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png'),
       (99, 'Kingler', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png'),
       (100, 'Voltorb', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png'),
       (101, 'Electrode', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png'),
       (102, 'Exeggcute', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png'),
       (103, 'Exeggutor', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png'),
       (104, 'Cubone', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png'),
       (105, 'Marowak', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png'),
       (106, 'Hitmonlee', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png'),
       (107, 'Hitmonchan', 'Fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png'),
       (108, 'Lickitung', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png'),
       (109, 'Koffing', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png'),
        (110, 'Weezing', 'Poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png'),
        (111, 'Rhyhorn', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png'),
        (112, 'Rhydon', 'Ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png'),
        (113, 'Chansey', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png'),
        (114, 'Tangela', 'Grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png'),
        (115, 'Kangaskhan', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png'),
        (116, 'Horsea', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png'),
        (117, 'Seadra', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png'),
        (118, 'Goldeen', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png'),
        (119, 'Seaking', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png'),
        (120, 'Staryu', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png'),
        (121, 'Starmie', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png'),
        (122, 'Mr. Mime', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png'),
        (123, 'Scyther', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png'),
        (124, 'Jynx', 'Ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png'),
        (125, 'Electabuzz', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png'),
        (126, 'Magmar', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png'),
        (127, 'Pinsir', 'Bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png'),
        (128, 'Tauros', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png'),
        (129, 'Magikarp', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png'),
        (130, 'Gyarados', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png'),
        (131, 'Lapras', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png'),
        (132, 'Ditto', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png'),
        (133, 'Eevee', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png'),
        (134, 'Vaporeon', 'Water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png'),
        (135, 'Jolteon', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png'),
        (136, 'Flareon', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png'),
        (137, 'Porygon', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png'),
        (138, 'Omanyte', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png'),
        (139, 'Omastar', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png'),
        (140, 'Kabuto', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png'),
        (141, 'Kabutops', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png'),
        (142, 'Aerodactyl', 'Rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png'),
        (143, 'Snorlax', 'Normal', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png'),
        (144, 'Articuno', 'Ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png'),
        (145, 'Zapdos', 'Electric', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png'),
        (146, 'Moltres', 'Fire', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png'),
        (147, 'Dratini', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png'),
        (148, 'Dragonair', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png'),
        (149, 'Dragonite', 'Dragon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png'),
        (150, 'Mewtwo', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png'),
        (151, 'Mew', 'Psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png');
       
